name: Super-Linter

on:

  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  lint:

    name: Lint the code
    runs-on: ubuntu-latest

    permissions:
      contents: read  # for actions/checkout to fetch code
      statuses: write # for github/super-linter/slim to mark status of each linter run

    steps:

      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0


      - name: Run Super-Linter
        uses: github/super-linter/slim@45fc0d88288beee4701c62761281edfee85655d7 # v5.0.0
        env:
          DEFAULT_BRANCH: main

          SUPPRESS_POSSUM: true

          VALIDATE_ALL_CODEBASE: ${{ !contains(github.event_name, 'pull_request') }}
          VALIDATE_PYTHON: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_GITHUB_ACTIONS: true

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}